export interface Profile {
    username: string,
    password: string,
    firstName: string,
    lastName: string,
    phoneNumber: string,
    bvn: number,
    nin: string,
    age: string,
    occupation: string,
    salary: string,
    maritalStatus: string,
    address: string,
    accountNumber: string,
    bank: string,
    origin: string,
    nextOfKinName: string,
    nextOfKinPhoneNumber: string,
    wallet: Object,
    messages: Array<string>,
    pendingTransfer: Boolean
}